/**
 * Database Types
 *
 * TypeScript types for Supabase database schema.
 * These will eventually be auto-generated by: npx supabase gen types typescript
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      widget_templates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: string;
          config_schema: Json;
          is_declarative: boolean;
          declarative_template: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          category: string;
          config_schema: Json;
          is_declarative?: boolean;
          declarative_template?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          config_schema?: Json;
          is_declarative?: boolean;
          declarative_template?: Json | null;
          created_at?: string;
        };
      };
      widget_instances: {
        Row: {
          id: string;
          user_id: string;
          template_id: string | null;
          position: Json;
          config: Json;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          template_id?: string | null;
          position: Json;
          config: Json;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          template_id?: string | null;
          position?: Json;
          config?: Json;
          status?: string;
          created_at?: string;
        };
      };
      widget_secrets: {
        Row: {
          id: string;
          user_id: string;
          secret_name: string;
          secret_value: string; // Encrypted by Supabase Vault
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          secret_name: string;
          secret_value: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          secret_name?: string;
          secret_value?: string;
          created_at?: string;
        };
      };
      conversation_history: {
        Row: {
          id: string;
          user_id: string;
          session_id: string;
          role: 'user' | 'assistant';
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_id: string;
          role: 'user' | 'assistant';
          content: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_id?: string;
          role?: 'user' | 'assistant';
          content?: string;
          created_at?: string;
        };
      };
      dashboard_checkpoints: {
        Row: {
          id: string;
          user_id: string;
          snapshot: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          snapshot: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          snapshot?: Json;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

/**
 * Helper types for easier use
 */
export type WidgetTemplate = Database['public']['Tables']['widget_templates']['Row'];
export type WidgetInstance = Database['public']['Tables']['widget_instances']['Row'];
export type WidgetSecret = Database['public']['Tables']['widget_secrets']['Row'];
export type ConversationMessage = Database['public']['Tables']['conversation_history']['Row'];
export type DashboardCheckpoint = Database['public']['Tables']['dashboard_checkpoints']['Row'];

/**
 * Widget position for react-grid-layout
 */
export interface WidgetPosition {
  x: number;
  y: number;
  w: number;
  h: number;
  i: string; // widget instance ID
}

/**
 * Widget configuration
 */
export interface WidgetConfig {
  [key: string]: any;
}

/**
 * Dashboard snapshot for checkpoints
 */
export interface DashboardSnapshot {
  layout: WidgetPosition[];
  widgets: Record<string, WidgetConfig>;
  timestamp: string;
}
